### ISSUE TITLE
Action fails with Type 'string' is not assignalbe to type 'string[] | null.'

### ISSUE THREAD

**Issue by slackline** [ikoamu/publish-org-roam-ui#6]
Thanks for writing and sharing this action going to be so useful to have the notes hosted on GitHub pages and updated when pushes are made.

I've had a go at setting things up but the action fails (full [failed job log](https://github.com/slackline/org-roam/actions/runs/8508433202/job/23301980712)).

It may be an upstream issue but on reading carefully I think it might have something to do with the headers I have in my files as whilst the final reported error is as per the title (`Type 'string' is not assignable to type 'string[] | null'.`) I see there are a number of fields that are undefined (`TITLE`, `FILE`, `CTIME`, `MTIME`, `ROAM_ALIASES` and 4 more, one of which I can hazard a guess will be `FILETAGS`).

```
./pages/index.tsx:351:23
Type error: Argument of type '{ nodes: ({ tags: string[]; properties: { CATEGORY: string; CTIME: string; MTIME: string; ID: string; BLOCKED: string; ALLTAGS: string; PRIORITY: string; ITEM?: undefined; FILE?: undefined; ROAM_ALIASES?: undefined; ... 4 more ...; TITLE?: undefined; }; ... 5 more ...; id: string; } | ... 18 more ... | { ...; })[]; ...' is not assignable to parameter of type 'OrgRoamGraphReponse'.
  Types of property 'nodes' are incompatible.
    Type '({ tags: string[]; properties: { CATEGORY: string; CTIME: string; MTIME: string; ID: string; BLOCKED: string; ALLTAGS: string; PRIORITY: string; ITEM?: undefined; FILE?: undefined; ROAM_ALIASES?: undefined; ... 4 more ...; TITLE?: undefined; }; ... 5 more ...; id: string; } | ... 18 more ... | { ...; })[]' is not assignable to type 'OrgRoamNode[]'.
      Type '{ tags: string[]; properties: { CATEGORY: string; CTIME: string; MTIME: string; ID: string; BLOCKED: string; ALLTAGS: string; PRIORITY: string; ITEM?: undefined; FILE?: undefined; ROAM_ALIASES?: undefined; ... 4 more ...; TITLE?: undefined; }; ... 5 more ...; id: string; } | ... 18 more ... | { ...; }' is not assignable to type 'OrgRoamNode'.
        Type '{ tags: string[]; properties: { CATEGORY: string; ID: string; BLOCKED: string; ALLTAGS: string; PRIORITY: string; ITEM: string; CTIME?: undefined; MTIME?: undefined; FILE?: undefined; ROAM_ALIASES?: undefined; ... 4 more ...; TITLE?: undefined; }; ... 5 more ...; id: string; }' is not assignable to type 'OrgRoamNode'.
          Types of property 'olp' are incompatible.
            Type 'string' is not assignable to type 'string[] | null'.

  349 |   useEffect(() => {
  350 |     if (!graphData) {
> 351 |       updateGraphData(graphDataJson.data)
      |                       ^
  352 |       return
  353 |     }
  354 |     currentGraphDataRef.current = graphData
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.22
$ next export -o standalone/out/
info  - Loaded env from /home/runner/work/org-roam/org-roam/ui/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
info  - using build directory: /home/runner/work/org-roam/org-roam/ui/build
Error: Could not find a production build in the '/home/runner/work/org-roam/org-roam/ui/build' directory. Try building your app with 'next build' before starting the static export. https://nextjs.org/docs/messages/next-export-no-build-id
    at /home/runner/work/org-roam/org-roam/ui/node_modules/next/dist/export/index.js:158:19
    at async Span.traceAsyncFn (/home/runner/work/org-roam/org-roam/ui/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
patching file ../pages/index.tsx
Hunk #2 succeeded at 347 (offset 1 line).
Hunk #3 succeeded at 429 (offset 1 line).
patching file ../util/uniorg.tsx
Hunk #1 succeeded at 37 (offset 1 line).
patching file ../components/Sidebar/Link.tsx
Hunk #1 succeeded at 151 (offset -1 lines).
patching file ../components/Sidebar/OrgImage.tsx
patching file ../components/Tweaks/Behavior/BehaviorPanel.tsx
patching file ../components/contextmenu.tsx
Run touch ./standalone/out/.nojekyll
touch: cannot touch './standalone/out/.nojekyll': No such file or directory
Error: Process completed with exit code 1.
```	

The `MTIME` and `CTIME` stem from use of [`org-roam-timestamps`](https://github.com/tefkah/org-roam-timestamps) and I'll typically set `#+TITLE:` and `#+FILETAGS:` in every file to aid categorisation and finding things, e.g.

```
:PROPERTIES:
:ID:       0e6300c6-7025-4f45-820d-4d9da82b41a6
:mtime:    20240304160438 20240302204630 20240121200503 20240121115714 20240107103825 20231219213305 20231126221347 20231121204845 20231120130321 20231015172332 20231005133759 20230926220759 20230917083604 20230905212306 20230724174038
:ctime:    20230724174038
:END:
#+TITLE: Linux
#+FILETAGS: :linux:computing:foss:opensource:
```

Types for `TITLE` and `FILETAGS` should be strings `MTIME` and `CTIME` notionally strings but they could perhaps be `Date()` (not too hot on TypeScript I'm afraid).

**Comment by slackline** [comment]
Thanks for the quick response.

I'd jumped back to trying main after tinkering yesterday and it still failed. Just tried again and it now [fails at `actions/deploy-pages@v4` with a complaint about tokens](https://github.com/slackline/org-roam/actions/runs/8512555370/job/23362222337) so that is something on my side i need to tweak in the configuration/settings.

Thanks for writing and sharing really appreciate the effort that this takes, particularly for side projects done in spare time.

**Comment by slackline** [comment]
Double checked the `README.md` and have ensured _Settings > Pages_ is set to _Deploy from Branch_ and the branch is set to `main` and `/ root` but no joy.

The artefact builds but fails to [deploy](https://github.com/slackline/org-roam/actions/runs/8534439826/job/23378921033) but I'm unsure why as the status page mentioned is working.

Am I missing out a key stage with access tokens perhaps? I've a few other sites I host/deploy on GitHub pages but none have required such access tokens (they do deploy using different Actions though).

**Comment by slackline** [comment]
Thank you so much for these pointers :+1:  I'll try them out in a day or so (busy with work today and out this evening).

**Comment by slackline** [comment]
[Success!](https://org-roam.nshephard.dev/) :smile: 

Main problem was that when enabling GitHub Pages I'd set to _Deploy from branch_ when it should have been _Deploy from Action_. Obvious in hindsight :facepalm:
